kind: pipeline
# type: docker
name: default

steps:
- name: test
  image: juliantoro/fastapibase
  commands:
  - sleep 20
  - pip install -r src/requirements.txt  
  - pytest .  
  environment:
    DATABASE_URL: mysql://dbmysql/automation
    AIRTABLE_API_KEY:
      from_secret: AIRTABLE_API_KEY
    AIRTABLE_BASE:
      from_secret: AIRTABLE_BASE

- name: testdocker
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - sleep 10 # give docker enough time to start
  - docker ps -a

volumes:
- name: dockersock
  temp: {}

# - name: "packer"
#   image: appleboy/drone-packer
#   settings:
#     template: template.json
#     actions: build

services:
- name: dbmysql
  image: mysql
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: automation

- name: docker
  image: docker:dind
  privileged: true 
  volumes:
  - name: dockersock
    path: /var/run