kind: pipeline
# type: docker
name: default

steps:
- name: test
  image: juliantoro/fastapibase
  commands:
  - sleep 20
  - pip install -r src/requirements.txt  
  - pytest .  
  environment:
    DATABASE_URL: mysql://dbmysql/automation
    AIRTABLE_API_KEY:
      from_secret: AIRTABLE_API_KEY
    AIRTABLE_BASE:
      from_secret: AIRTABLE_BASE

- name: docker  
  image: plugins/docker
  settings:
    repo: juliantoro/automationrapigo
    username: juliantoro
    password: 
      from_secret: PASSWORD_DOCKERHUB
  when:
    branch:
    - master
    - hotfix
    - feature/*

# - name: testdocker
#   image: docker:dind
#   volumes:
#   - name: dockersock
#     path: /var/run
#   commands:
#   - sleep 5 # give docker enough time to start
#   - ls
#   - docker ps -a
#   - docker build .

# volumes:
# - name: dockersock
#   temp: {}

services:
- name: dbmysql
  image: mysql
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: automation

# - name: docker
#   image: docker:dind
#   privileged: true 
#   volumes:
#   - name: dockersock
#     path: /var/run