kind: pipeline
type: docker
name: default

steps:
- name: test
  image: juliantoro/fastapibase
  commands:
  - sleep 20
  - pip install -r src/requirements.txt  
  - pytest .
  environment:
    AIRTABLE_API_KEY:
      from_secret: AIRTABLE_API_KEY
    AIRTABLE_BASE:
      from_secret: AIRTABLE_BASE

# - name: "packer"
#   image: appleboy/drone-packer
#   settings:
#     template: template.json
#     actions: build

services:
- name: dbmysql
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: example
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: automation
    MYSQL_USER: admin
    MYSQL_PASSWORD": example

# - name: testdocker
#   image: docker:dind
#   volumes:
#   - name: dockersock
#     path: /var/run
#   commands:
#   - sleep 10 # give docker enough time to start
#   - docker ps -a

# volumes:
# - name: dockersock
#   temp: {}