version: '2'
services:
  automationrapigo:
    image: juliantoro/automationrapigo
    stdin_open: true
    tty: true
    secrets:
    - mode: '0444'
      uid: '0'
      gid: '0'
      source: airtable_api_key
      target: table
    command:
    - uvicorn
    - app.main:app
    - --workers
    - '1'
    - --host
    - 0.0.0.0
    - --port
    - '8000'
    labels:
      io.rancher.container.pull_image: always
secrets:
  airtable_api_key:
    external: 'true'